apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cicd
  labels:
    app: hello-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-cicd
  template:
    metadata:
      labels:
        app: hello-cicd
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: web
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: VERSION_PLACEHOLDER
            - name: APP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hello-cicd-secrets
                  key: api-key
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
